/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package scms;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class purchase_product extends javax.swing.JFrame {

    /**
     * Creates new form purchase_product
     */
    public purchase_product() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        q1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        q2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        q3 = new javax.swing.JTextField();
        q4 = new javax.swing.JTextField();
        q5 = new javax.swing.JTextField();
        q6 = new javax.swing.JTextField();
        q7 = new javax.swing.JTextField();
        q8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        q9 = new javax.swing.JTextField();
        q10 = new javax.swing.JTextField();
        q11 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        q14 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        q15 = new javax.swing.JTextField();
        ccid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(16, 1, 45));

        jLabel2.setBackground(new java.awt.Color(255, 204, 51));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("CAR SERVICE MANAGEMENT SYSTEM");

        jLabel1.setBackground(new java.awt.Color(153, 153, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setText("To get services , Enter Customer ID:");

        jCheckBox2.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 0));
        jCheckBox2.setText("WASH & CLEAN");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(255, 255, 0));
        jCheckBox3.setText("OIL/OIL FILTER");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(255, 204, 0));
        jCheckBox4.setText("WIPER BLADES REPLACEMENT");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(255, 204, 0));
        jCheckBox5.setText("AIR FILTER REPLACEMENT");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox6.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(255, 204, 0));
        jCheckBox6.setText("NEW TIRES");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jCheckBox7.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBox7.setForeground(new java.awt.Color(255, 204, 0));
        jCheckBox7.setText("BATTERY REPLACEMENT");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        jCheckBox8.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBox8.setForeground(new java.awt.Color(255, 204, 0));
        jCheckBox8.setText("BRAKE WORK");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        jCheckBox13.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBox13.setForeground(new java.awt.Color(255, 204, 0));
        jCheckBox13.setText("ENGINE TUNE-UP");
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });

        jCheckBox14.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBox14.setForeground(new java.awt.Color(255, 204, 0));
        jCheckBox14.setText("WHEELS ALIGNED / BALANCED");
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });

        jCheckBox15.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBox15.setForeground(new java.awt.Color(255, 204, 0));
        jCheckBox15.setText("AIR CONDITIONING SYSTEM");
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });

        jCheckBox19.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBox19.setForeground(new java.awt.Color(255, 204, 0));
        jCheckBox19.setText("FIXING GLASS");
        jCheckBox19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox19ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText(" DEVELOPED BY MUAAZ BIN ZAHID(20CSE039)");

        jCheckBox20.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBox20.setForeground(new java.awt.Color(255, 204, 0));
        jCheckBox20.setText("COLORING");
        jCheckBox20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox20ActionPerformed(evt);
            }
        });

        jCheckBox21.setBackground(new java.awt.Color(0, 153, 153));
        jCheckBox21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBox21.setForeground(new java.awt.Color(255, 204, 0));
        jCheckBox21.setText("SEAT & COVERS");
        jCheckBox21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox21ActionPerformed(evt);
            }
        });

        q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("Quantity:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("Quantity:");

        q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 0));
        jLabel6.setText("Quantity:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 0));
        jLabel7.setText("Quantity:");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 0));
        jLabel8.setText("Quantity:");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 0));
        jLabel9.setText("Quantity:");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 0));
        jLabel10.setText("Quantity:");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 0));
        jLabel11.setText("Quantity:");

        q3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3ActionPerformed(evt);
            }
        });

        q4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4ActionPerformed(evt);
            }
        });

        q5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5ActionPerformed(evt);
            }
        });

        q6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q6ActionPerformed(evt);
            }
        });

        q7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q7ActionPerformed(evt);
            }
        });

        q8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q8ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 0));
        jLabel12.setText("Quantity:");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 0));
        jLabel13.setText("Quantity:");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 0));
        jLabel14.setText("Quantity:");

        q9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q9ActionPerformed(evt);
            }
        });

        q10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q10ActionPerformed(evt);
            }
        });

        q11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q11ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 204, 0));
        jLabel17.setText("Quantity:");

        q14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q14ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 204, 0));
        jLabel18.setText("Quantity:");

        q15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q15ActionPerformed(evt);
            }
        });

        ccid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccidActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 255));
        jButton1.setText("Continue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(8, 8, 8)
                                        .addComponent(q1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel10))
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(q6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(q7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCheckBox4, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(q4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBox13, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jCheckBox14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox15, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(q8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(q10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(q11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(q9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q15, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(q14, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(432, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(275, 275, 275)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jCheckBox8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(q5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(180, 180, 180)
                                        .addComponent(jCheckBox21, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel18))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ccid, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(468, 468, 468)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox13)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(q8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ccid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox2)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(q1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox14)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox15)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox4)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox19)
                    .addComponent(jCheckBox5)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox6)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox20)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox7)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox21)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox8)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addGap(0, 1944, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        // TODO add your handling code here:
                  
        
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox15ActionPerformed

    private void jCheckBox19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox19ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jCheckBox19ActionPerformed

    private void jCheckBox20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox20ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox20ActionPerformed

    private void jCheckBox21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox21ActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox21ActionPerformed
 Scanner sc = new Scanner(System.in);
    private void q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1ActionPerformed
        // TODO add your handling code here:
                int q = Integer.parseInt(q1.getText());
      
                   float totalcost = 2000*q;
 
       
               JOptionPane.showMessageDialog(null," cost= 2000BDT/unit\nTotal cost = "+totalcost+" .To get the service, click on 'OK'");
                      SimpleDateFormat simpleformat = new SimpleDateFormat("E, dd MMM yyyy HH:mm:ss");

                            simpleformat = new SimpleDateFormat("dd/MMMM/yyyy");
                            String strr = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("MMMM");
                            String strMonth = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("HH.mm.ss");
                            String strTime = simpleformat.format(new Date());
                            
                           
                            
                            
                int cusid = Integer.parseInt(ccid.getText());   
                      
                try{
                    
         Class.forName("com.mysql.jdbc.Driver");
         Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/csms","root","");
  Statement stmt = conn.createStatement();
   ResultSet rs = stmt.executeQuery("SELECT customer_name FROM customer_details WHERE customer_id ='"+cusid+"' ");
   rs.next();
   String c_name = rs.getString("customer_name");
   
 
  String sql1 = "INSERT INTO expenditure VALUES(?,?,?,?,?,?,?,?,?,?)";     
PreparedStatement pst = conn.prepareStatement(sql1);

pst.setString(1,ccid.getText());
pst.setString(2, c_name);
pst.setString(3,"101");
pst.setString(4,"WASH & CLEAN");
pst.setString(5,"2000");
pst.setInt(6, q);
pst.setFloat(7,totalcost);
pst.setString(8,strr);
pst.setString(9,strTime);  
pst.setString(10,strMonth);
pst.executeUpdate();
JOptionPane.showMessageDialog(this,"Data stored successfully!!"); 
 conn.close();
       }
       
       catch ( Exception e)
       {
           JOptionPane.showMessageDialog(this,e); 
       }
             purchase_product pd1 = new purchase_product();
                pd1.setVisible(true);
          
          
    }//GEN-LAST:event_q1ActionPerformed

    private void q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2ActionPerformed
        // TODO add your handling code here:
        int q = Integer.parseInt(q2.getText());
      
       float totalcost = 1500*q;
               JOptionPane.showMessageDialog(null," cost= 1500BDT/unit\nTotal cost = "+totalcost+" .To get the service, click on 'OK'");
               
               SimpleDateFormat simpleformat = new SimpleDateFormat("E, dd MMM yyyy HH:mm:ss");

                            simpleformat = new SimpleDateFormat("dd/MMMM/yyyy");
                            String strr = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("MMMM");
                            String strMonth = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("HH.mm.ss");
                            String strTime = simpleformat.format(new Date());
                            
                           
                            
                            
                int cusid = Integer.parseInt(ccid.getText());   
                      
                try{
                    
         Class.forName("com.mysql.jdbc.Driver");
         Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/csms","root","");
  Statement stmt = conn.createStatement();
   ResultSet rs = stmt.executeQuery("SELECT customer_name FROM customer_details WHERE customer_id ='"+cusid+"' ");
   rs.next();
   String c_name = rs.getString("customer_name");
   
 
  String sql1 = "INSERT INTO expenditure VALUES(?,?,?,?,?,?,?,?,?,?)";     
PreparedStatement pst = conn.prepareStatement(sql1);

pst.setString(1,ccid.getText());
pst.setString(2, c_name);
pst.setString(3,"102");
pst.setString(4,"OIL/OIL FILTER");
pst.setString(5,"1500");
pst.setInt(6, q);
pst.setFloat(7,totalcost);
pst.setString(8,strr);
pst.setString(9,strTime);  
pst.setString(10,strMonth);
pst.executeUpdate();
JOptionPane.showMessageDialog(this,"Data stored successfully!!"); 
 conn.close();
       }
        catch ( Exception e)
       {
           JOptionPane.showMessageDialog(this,e); 
       }
           
             purchase_product pd1 = new purchase_product();
                pd1.setVisible(true);
    }//GEN-LAST:event_q2ActionPerformed

    private void q3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3ActionPerformed
        // TODO add your handling code here:
        int q = Integer.parseInt(q3.getText());
        float totalcost = 3000*q;
               JOptionPane.showMessageDialog(null," cost= 3000BDT/unit\nTotal cost = "+totalcost+" .To get the service, click on 'OK'");
                        SimpleDateFormat simpleformat = new SimpleDateFormat("E, dd MMM yyyy HH:mm:ss");

                            simpleformat = new SimpleDateFormat("dd/MMMM/yyyy");
                            String strr = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("MMMM");
                            String strMonth = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("HH.mm.ss");
                            String strTime = simpleformat.format(new Date());
                            
                           
                            
                            
                int cusid = Integer.parseInt(ccid.getText());   
                      
                try{
                    
         Class.forName("com.mysql.jdbc.Driver");
         Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/csms","root","");
  Statement stmt = conn.createStatement();
   ResultSet rs = stmt.executeQuery("SELECT customer_name FROM customer_details WHERE customer_id ='"+cusid+"' ");
   rs.next();
   String c_name = rs.getString("customer_name");
   
 
  String sql1 = "INSERT INTO expenditure VALUES(?,?,?,?,?,?,?,?,?,?)";     
PreparedStatement pst = conn.prepareStatement(sql1);

pst.setString(1,ccid.getText());
pst.setString(2, c_name);
pst.setString(3,"103");
pst.setString(4,"WIPER BLADES REPLACEMENT");
pst.setString(5,"3000");
pst.setInt(6, q);
pst.setFloat(7,totalcost);
pst.setString(8,strr);
pst.setString(9,strTime);  
pst.setString(10,strMonth);
pst.executeUpdate();
JOptionPane.showMessageDialog(this,"Data stored successfully!!"); 
 conn.close();
       }
        catch ( Exception e)
       {
           JOptionPane.showMessageDialog(this,e); 
       }
             purchase_product pd1 = new purchase_product();
                pd1.setVisible(true);
    }//GEN-LAST:event_q3ActionPerformed

    private void q4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4ActionPerformed
        // TODO add your handling code here:
         int q = Integer.parseInt(q4.getText());
        float totalcost = 3500*q;
                JOptionPane.showMessageDialog(null," cost= 3000BDT/unit\nTotal cost = "+totalcost+" .To get the service, click on 'OK'");
                              SimpleDateFormat simpleformat = new SimpleDateFormat("E, dd MMM yyyy HH:mm:ss");

                            simpleformat = new SimpleDateFormat("dd/MMMM/yyyy");
                            String strr = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("MMMM");
                            String strMonth = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("HH.mm.ss");
                            String strTime = simpleformat.format(new Date());
                            
                           
                            
                            
                int cusid = Integer.parseInt(ccid.getText());   
                      
                try{
                    
         Class.forName("com.mysql.jdbc.Driver");
         Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/csms","root","");
  Statement stmt = conn.createStatement();
   ResultSet rs = stmt.executeQuery("SELECT customer_name FROM customer_details WHERE customer_id ='"+cusid+"' ");
   rs.next();
   String c_name = rs.getString("customer_name");
   
 
  String sql1 = "INSERT INTO expenditure VALUES(?,?,?,?,?,?,?,?,?,?)";     
PreparedStatement pst = conn.prepareStatement(sql1);

pst.setString(1,ccid.getText());
pst.setString(2, c_name);
pst.setString(3,"104");
pst.setString(4,"AIR FILTER REPLACEMENT");
pst.setString(5,"3500");
pst.setInt(6, q);
pst.setFloat(7,totalcost);
pst.setString(8,strr);
pst.setString(9,strTime);  
pst.setString(10,strMonth);
pst.executeUpdate();
JOptionPane.showMessageDialog(this,"Data stored successfully!!"); 
 conn.close();
       }
        catch ( Exception e)
       {
           JOptionPane.showMessageDialog(this,e); 
       }
                  purchase_product pd1 = new purchase_product();
                pd1.setVisible(true);
    }//GEN-LAST:event_q4ActionPerformed

    private void q5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5ActionPerformed
        // TODO add your handling code here:
        int q = Integer.parseInt(q5.getText());
        float totalcost = 4500*q;
                JOptionPane.showMessageDialog(null," cost= 4500BDT/unit\nTotal cost = "+totalcost+" .To get the service, click on 'OK'");
                            SimpleDateFormat simpleformat = new SimpleDateFormat("E, dd MMM yyyy HH:mm:ss");

                            simpleformat = new SimpleDateFormat("dd/MMMM/yyyy");
                            String strr = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("MMMM");
                            String strMonth = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("HH.mm.ss");
                            String strTime = simpleformat.format(new Date());
                            
                           
                            
                            
                int cusid = Integer.parseInt(ccid.getText());   
                      
                try{
                    
         Class.forName("com.mysql.jdbc.Driver");
         Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/csms","root","");
  Statement stmt = conn.createStatement();
   ResultSet rs = stmt.executeQuery("SELECT customer_name FROM customer_details WHERE customer_id ='"+cusid+"' ");
   rs.next();
   String c_name = rs.getString("customer_name");
   
 
  String sql1 = "INSERT INTO expenditure VALUES(?,?,?,?,?,?,?,?,?,?)";     
PreparedStatement pst = conn.prepareStatement(sql1);

pst.setString(1,ccid.getText());
pst.setString(2, c_name);
pst.setString(3,"105");
pst.setString(4,"NEW TIRES");
pst.setString(5,"4500");
pst.setInt(6, q);
pst.setFloat(7,totalcost);
pst.setString(8,strr);
pst.setString(9,strTime);  
pst.setString(10,strMonth);
pst.executeUpdate();
JOptionPane.showMessageDialog(this,"Data stored successfully!!"); 
 conn.close();
       }
        catch ( Exception e)
       {
           JOptionPane.showMessageDialog(this,e); 
       }
                   purchase_product pd1 = new purchase_product();
                pd1.setVisible(true);
    }//GEN-LAST:event_q5ActionPerformed

    private void q6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q6ActionPerformed
        // TODO add your handling code here:
         int q = Integer.parseInt(q6.getText());
        float totalcost = 5000*q;
                JOptionPane.showMessageDialog(null," cost= 5000BDT/unit\nTotal cost = "+totalcost+" .To get the service, click on 'OK'");
                         SimpleDateFormat simpleformat = new SimpleDateFormat("E, dd MMM yyyy HH:mm:ss");

                            simpleformat = new SimpleDateFormat("dd/MMMM/yyyy");
                            String strr = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("MMMM");
                            String strMonth = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("HH.mm.ss");
                            String strTime = simpleformat.format(new Date());
                            
                           
                            
                            
                int cusid = Integer.parseInt(ccid.getText());   
                      
                try{
                    
         Class.forName("com.mysql.jdbc.Driver");
         Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/csms","root","");
  Statement stmt = conn.createStatement();
   ResultSet rs = stmt.executeQuery("SELECT customer_name FROM customer_details WHERE customer_id ='"+cusid+"' ");
   rs.next();
   String c_name = rs.getString("customer_name");
   
 
  String sql1 = "INSERT INTO expenditure VALUES(?,?,?,?,?,?,?,?,?,?)";     
PreparedStatement pst = conn.prepareStatement(sql1);

pst.setString(1,ccid.getText());
pst.setString(2, c_name);
pst.setString(3,"106");
pst.setString(4,"BATTERY REPLACEMENT");
pst.setString(5,"2000");
pst.setInt(6, q);
pst.setFloat(7,totalcost);
pst.setString(8,strr);
pst.setString(9,strTime);  
pst.setString(10,strMonth);
pst.executeUpdate();
JOptionPane.showMessageDialog(this,"Data stored successfully!!"); 
 conn.close();
       }
        catch ( Exception e)
       {
           JOptionPane.showMessageDialog(this,e); 
       }   
             purchase_product pd1 = new purchase_product();
                pd1.setVisible(true);
    }//GEN-LAST:event_q6ActionPerformed

    private void q7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q7ActionPerformed
        // TODO add your handling code here:
         int q = Integer.parseInt(q7.getText());
        float totalcost = 1500*q;
                JOptionPane.showMessageDialog(null," cost= 1500BDT/unit\nTotal cost = "+totalcost+" .To get the service, click on 'OK'");
                           SimpleDateFormat simpleformat = new SimpleDateFormat("E, dd MMM yyyy HH:mm:ss");

                            simpleformat = new SimpleDateFormat("dd/MMMM/yyyy");
                            String strr = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("MMMM");
                            String strMonth = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("HH.mm.ss");
                            String strTime = simpleformat.format(new Date());
                            
                           
                            
                            
                int cusid = Integer.parseInt(ccid.getText());   
                      
                try{
                    
         Class.forName("com.mysql.jdbc.Driver");
         Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/csms","root","");
  Statement stmt = conn.createStatement();
   ResultSet rs = stmt.executeQuery("SELECT customer_name FROM customer_details WHERE customer_id ='"+cusid+"' ");
   rs.next();
   String c_name = rs.getString("customer_name");
   
 
  String sql1 = "INSERT INTO expenditure VALUES(?,?,?,?,?,?,?,?,?,?)";     
PreparedStatement pst = conn.prepareStatement(sql1);

pst.setString(1,ccid.getText());
pst.setString(2, c_name);
pst.setString(3,"107");
pst.setString(4,"BRAKE WORK");
pst.setString(5,"1500");
pst.setInt(6, q);
pst.setFloat(7,totalcost);
pst.setString(8,strr);
pst.setString(9,strTime);  
pst.setString(10,strMonth);
pst.executeUpdate();
JOptionPane.showMessageDialog(this,"Data stored successfully!!"); 
 conn.close();
       }
        catch ( Exception e)
       {
           JOptionPane.showMessageDialog(this,e); 
       }
                       purchase_product pd1 = new purchase_product();
                pd1.setVisible(true);
    }//GEN-LAST:event_q7ActionPerformed

    private void q8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q8ActionPerformed
        // TODO add your handling code here:
int q = Integer.parseInt(q8.getText());
        float totalcost = 1500*q;
                JOptionPane.showMessageDialog(null," cost= 1500BDT/unit\nTotal cost = "+totalcost+" .To get the service, click on 'OK'");
              SimpleDateFormat simpleformat = new SimpleDateFormat("E, dd MMM yyyy HH:mm:ss");

                            simpleformat = new SimpleDateFormat("dd/MMMM/yyyy");
                            String strr = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("MMMM");
                            String strMonth = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("HH.mm.ss");
                            String strTime = simpleformat.format(new Date());
                            
                           
                            
                            
                int cusid = Integer.parseInt(ccid.getText());   
                      
                try{
                    
         Class.forName("com.mysql.jdbc.Driver");
         Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/csms","root","");
  Statement stmt = conn.createStatement();
   ResultSet rs = stmt.executeQuery("SELECT customer_name FROM customer_details WHERE customer_id ='"+cusid+"' ");
   rs.next();
   String c_name = rs.getString("customer_name");
   
 
  String sql1 = "INSERT INTO expenditure VALUES(?,?,?,?,?,?,?,?,?,?)";     
PreparedStatement pst = conn.prepareStatement(sql1);

pst.setString(1,ccid.getText());
pst.setString(2, c_name);
pst.setString(3,"108");
pst.setString(4,"ENGINE TUNE-UP");
pst.setString(5,"4000");
pst.setInt(6, q);
pst.setFloat(7,totalcost);
pst.setString(8,strr);
pst.setString(9,strTime);  
pst.setString(10,strMonth);
pst.executeUpdate();
JOptionPane.showMessageDialog(this,"Data stored successfully!!"); 
 conn.close();
       }
        catch ( Exception e)
       {
           JOptionPane.showMessageDialog(this,e); 
       }
                   
            purchase_product pd1 = new purchase_product();
                pd1.setVisible(true);
    }//GEN-LAST:event_q8ActionPerformed

    private void q9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q9ActionPerformed
        // TODO add your handling code here:
        int q = Integer.parseInt(q9.getText());
        float totalcost = 5000*q;
                JOptionPane.showMessageDialog(null," cost= 5000BDT/unit\nTotal cost = "+totalcost+" .To get the service, click on 'OK'");

                            SimpleDateFormat simpleformat = new SimpleDateFormat("E, dd MMM yyyy HH:mm:ss");

                            simpleformat = new SimpleDateFormat("dd/MMMM/yyyy");
                            String strr = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("MMMM");
                            String strMonth = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("HH.mm.ss");
                            String strTime = simpleformat.format(new Date());
                            
                           
                            
                            
                int cusid = Integer.parseInt(ccid.getText());   
                      
                try{
                    
         Class.forName("com.mysql.jdbc.Driver");
         Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/csms","root","");
  Statement stmt = conn.createStatement();
   ResultSet rs = stmt.executeQuery("SELECT customer_name FROM customer_details WHERE customer_id ='"+cusid+"' ");
   rs.next();
   String c_name = rs.getString("customer_name");
   
 
  String sql1 = "INSERT INTO expenditure VALUES(?,?,?,?,?,?,?,?,?,?)";     
PreparedStatement pst = conn.prepareStatement(sql1);

pst.setString(1,ccid.getText());
pst.setString(2, c_name);
pst.setString(3,"109");
pst.setString(4,"WHEELS ALIGNED / BALANCED");
pst.setString(5,"5000");
pst.setInt(6, q);
pst.setFloat(7,totalcost);
pst.setString(8,strr);
pst.setString(9,strTime);  
pst.setString(10,strMonth);
pst.executeUpdate();
JOptionPane.showMessageDialog(this,"Data stored successfully!!"); 
 conn.close();
       }
        catch ( Exception e)
       {
           JOptionPane.showMessageDialog(this,e); 
       } 
                
                purchase_product pd1 = new purchase_product();
                pd1.setVisible(true);
    
    }//GEN-LAST:event_q9ActionPerformed

    private void q10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q10ActionPerformed
        // TODO add your handling code here:
        int q = Integer.parseInt(q10.getText());
        float totalcost = 2000*q;
                JOptionPane.showMessageDialog(null," cost= 2000BDT/unit\nTotal cost = "+totalcost+" .To get the service, click on 'OK'");
              SimpleDateFormat simpleformat = new SimpleDateFormat("E, dd MMM yyyy HH:mm:ss");

                            simpleformat = new SimpleDateFormat("dd/MMMM/yyyy");
                            String strr = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("MMMM");
                            String strMonth = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("HH.mm.ss");
                            String strTime = simpleformat.format(new Date());
                            
                           
                            
                            
                int cusid = Integer.parseInt(ccid.getText());   
                      
                try{
                    
         Class.forName("com.mysql.jdbc.Driver");
         Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/csms","root","");
  Statement stmt = conn.createStatement();
   ResultSet rs = stmt.executeQuery("SELECT customer_name FROM customer_details WHERE customer_id ='"+cusid+"' ");
   rs.next();
   String c_name = rs.getString("customer_name");
   
 
  String sql1 = "INSERT INTO expenditure VALUES(?,?,?,?,?,?,?,?,?,?)";     
PreparedStatement pst = conn.prepareStatement(sql1);

pst.setString(1,ccid.getText());
pst.setString(2, c_name);
pst.setString(3,"110");
pst.setString(4,"AIR CONDITIONING SYSTEM");
pst.setString(5,"2000");
pst.setInt(6, q);
pst.setFloat(7,totalcost);
pst.setString(8,strr);
pst.setString(9,strTime);  
pst.setString(10,strMonth);
pst.executeUpdate();
JOptionPane.showMessageDialog(this,"Data stored successfully!!"); 
 conn.close();
       }
        catch ( Exception e)
       {
           JOptionPane.showMessageDialog(this,e); 
       }
                   
             purchase_product pd1 = new purchase_product();
             pd1.setVisible(true);
    }//GEN-LAST:event_q10ActionPerformed

    private void q11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q11ActionPerformed
        // TODO add your handling code here:
        int q = Integer.parseInt(q11.getText());
        float totalcost = 2500*q;
                JOptionPane.showMessageDialog(null," cost= 2500BDT/unit\nTotal cost = "+totalcost+" .To get the service, click on 'OK'");
                        SimpleDateFormat simpleformat = new SimpleDateFormat("E, dd MMM yyyy HH:mm:ss");

                            simpleformat = new SimpleDateFormat("dd/MMMM/yyyy");
                            String strr = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("MMMM");
                            String strMonth = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("HH.mm.ss");
                            String strTime = simpleformat.format(new Date());
                            
                           
                            
                            
                int cusid = Integer.parseInt(ccid.getText());   
                      
                try{
                    
         Class.forName("com.mysql.jdbc.Driver");
         Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/csms","root","");
  Statement stmt = conn.createStatement();
   ResultSet rs = stmt.executeQuery("SELECT customer_name FROM customer_details WHERE customer_id ='"+cusid+"' ");
   rs.next();
   String c_name = rs.getString("customer_name");
   
 
  String sql1 = "INSERT INTO expenditure VALUES(?,?,?,?,?,?,?,?,?,?)";     
PreparedStatement pst = conn.prepareStatement(sql1);

pst.setString(1,ccid.getText());
pst.setString(2, c_name);
pst.setString(3,"111");
pst.setString(4,"FIXING GLASS");
pst.setString(5,"2500");
pst.setInt(6, q);
pst.setFloat(7,totalcost);
pst.setString(8,strr);
pst.setString(9,strTime);  
pst.setString(10,strMonth);
pst.executeUpdate();
JOptionPane.showMessageDialog(this,"Data stored successfully!!"); 
 conn.close();
       }
        catch ( Exception e)
       {
           JOptionPane.showMessageDialog(this,e); 
       }
                  purchase_product pd1 = new purchase_product();
                pd1.setVisible(true);
    }//GEN-LAST:event_q11ActionPerformed

    private void q14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q14ActionPerformed
        // TODO add your handling code here:
        int q = Integer.parseInt(q14.getText());
        float totalcost = 5000*q;
                JOptionPane.showMessageDialog(null," cost= 5000BDT/unit\nTotal cost = "+totalcost+" .To get the service, click on 'OK'");
                      SimpleDateFormat simpleformat = new SimpleDateFormat("E, dd MMM yyyy HH:mm:ss");

                            simpleformat = new SimpleDateFormat("dd/MMMM/yyyy");
                            String strr = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("MMMM");
                            String strMonth = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("HH.mm.ss");
                            String strTime = simpleformat.format(new Date());
                            
                           
                            
                            
                int cusid = Integer.parseInt(ccid.getText());   
                      
                try{
                    
         Class.forName("com.mysql.jdbc.Driver");
         Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/csms","root","");
  Statement stmt = conn.createStatement();
   ResultSet rs = stmt.executeQuery("SELECT customer_name FROM customer_details WHERE customer_id ='"+cusid+"' ");
   rs.next();
   String c_name = rs.getString("customer_name");
   
 
  String sql1 = "INSERT INTO expenditure VALUES(?,?,?,?,?,?,?,?,?,?)";     
PreparedStatement pst = conn.prepareStatement(sql1);

pst.setString(1,ccid.getText());
pst.setString(2, c_name);
pst.setString(3,"112");
pst.setString(4,"COLORING");
pst.setString(5,"5000");
pst.setInt(6, q);
pst.setFloat(7,totalcost);
pst.setString(8,strr);
pst.setString(9,strTime);  
pst.setString(10,strMonth);
pst.executeUpdate();
JOptionPane.showMessageDialog(this,"Data stored successfully!!"); 
 conn.close();
       }
        catch ( Exception e)
       {
           JOptionPane.showMessageDialog(this,e); 
       }
                   
                    purchase_product pd1 = new purchase_product();
                pd1.setVisible(true);
    }//GEN-LAST:event_q14ActionPerformed

    private void q15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q15ActionPerformed
        // TODO add your handling code here:
         int q = Integer.parseInt(q15.getText());
        float totalcost = 2500*q;
                JOptionPane.showMessageDialog(null," cost= 2500BDT/unit\nTotal cost = "+totalcost+" .To get the service, click on 'OK'");
       
                            SimpleDateFormat simpleformat = new SimpleDateFormat("E, dd MMM yyyy HH:mm:ss");

                            simpleformat = new SimpleDateFormat("dd/MMMM/yyyy");
                            String strr = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("MMMM");
                            String strMonth = simpleformat.format(new Date());

                            simpleformat = new SimpleDateFormat("HH.mm.ss");
                            String strTime = simpleformat.format(new Date());
                            
                           
                            
                            
                int cusid = Integer.parseInt(ccid.getText());   
                      
                try{
                    
         Class.forName("com.mysql.jdbc.Driver");
         Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/csms","root","");
  Statement stmt = conn.createStatement();
   ResultSet rs = stmt.executeQuery("SELECT customer_name FROM customer_details WHERE customer_id ='"+cusid+"' ");
   rs.next();
   String c_name = rs.getString("customer_name");
   
 
  String sql1 = "INSERT INTO expenditure VALUES(?,?,?,?,?,?,?,?,?,?)";     
PreparedStatement pst = conn.prepareStatement(sql1);

pst.setString(1,ccid.getText());
pst.setString(2, c_name);
pst.setString(3,"113");
pst.setString(4,"SEAT & COVERS");
pst.setString(5,"2500");
pst.setInt(6, q);
pst.setFloat(7,totalcost);
pst.setString(8,strr);
pst.setString(9,strTime);  
pst.setString(10,strMonth);
pst.executeUpdate();
JOptionPane.showMessageDialog(this,"Data stored successfully!!"); 
 conn.close();
       }
        catch ( Exception e)
       {
           JOptionPane.showMessageDialog(this,e); 
       }     
              purchase_product pd1 = new purchase_product();
                pd1.setVisible(true);
    }//GEN-LAST:event_q15ActionPerformed

    private void ccidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        payment pt = new payment();
         pt.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(purchase_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(purchase_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(purchase_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(purchase_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new purchase_product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField ccid;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField q1;
    private javax.swing.JTextField q10;
    private javax.swing.JTextField q11;
    private javax.swing.JTextField q14;
    private javax.swing.JTextField q15;
    private javax.swing.JTextField q2;
    private javax.swing.JTextField q3;
    private javax.swing.JTextField q4;
    private javax.swing.JTextField q5;
    private javax.swing.JTextField q6;
    private javax.swing.JTextField q7;
    private javax.swing.JTextField q8;
    private javax.swing.JTextField q9;
    // End of variables declaration//GEN-END:variables
}
